development:
  forest_env_secret: b7e86a1d9ee36382a2dee669257825ea79d57f07bde37cf0370ff89065940ee0
  forest_auth_secret: 3HdNpgUfG4OjNtrGJouYDg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
